function[] = estimateProxies(label, age, ensembleName, latName, lonName)
%% estimateProxies  Estimates proxy records for a particular time slice and ensemble
% ----------
%   estimateProxies(label, age, ensembleName, latName, lonName)
%   Estimates the proxy records for a particular time slice and ensemble.
%   Saves the proxy estimates to a NetCDF file in the current directory.
%   The name of saved file will follow the pattern <label>_estimates.nc
%
%   Proxy estimates are generated by running BaySPLINE (uk_forward.m),
%   BaySPAR (tex_forward.m), and BayMAG (baymag_forward_ln.m) on the UK'37,
%   TEX86, and Mg/Ca proxy records, respectively.
%
%   The inputs to the PSMs are located using the latitude-longitude
%   coordinates, or paleo-coordinates, associated with the time-slice being
%   estimated. Each PSM is passed inputs from a particular seasonal mean. 
%   Seasonal windows for the UK'37 record are calculated using the
%   "checkSeasonality.m" function in BaySPLINE. All TEX86 records use
%   annual mean values. Seasonal windows for Mg/Ca are calculated using the
%   "get_sea.m" function from BayMAG. The Mg/Ca PSMs also use parametrized
%   omega and pH values, which are calculated using the "omgph.m" function
%   from BayMAG.
% ----------
%   Inputs:
%       label (string scalar): A label to use for the estimates. The file
%           name for the NetCDF file will follow the pattern
%           <label>_estimates.nc
%       age (numeric scalar): The time metadata for the time slice in which
%           to estimate proxies. This value is used to implement the BayMAG
%           sea water correction. The time value should be in Ma.
%       ensembleName (string scalar): The label of the ensemble to use to
%           generate the proxy estimates.
%       latName (string scalar): The name of the site metadata to use as
%           latitude (paleo)coordinates. Specifically, this should be the name of
%           one of the site metadata columns from "proxies.nc"
%       lonName (string scalar): The name of the site metadata to use as
%           longitude (paleo)coordinates. Specifically, this should be the name of
%           one of the site metadata columns from "proxies.nc"
%
%   Outputs:
%       Creates a NetCDF file named "<label>_estimates.nc" in the current
%       directory.

% Error check data types of inputs
label = assertStrScalar(label, 'label');
assert(isnumeric(age)&&isscalar(age), 'age must be a numeric scalar');
ensembleName = assertStrScalar(ensembleName, 'ensembleName');
latName = assertStrScalar(latName, 'latName');
lonName = assertStrScalar(lonName, 'lonName');

% Get the proxy metadata, and identify the metadata in each column
proxies = gridfile('proxies').metadata;
columns = proxies.attributes.site_metadata_columns;
proxies = proxies.site;

% Locate the columns with the coordinate metadata
latColumn = strcmp(latName, columns);
lonColumn = strcmp(lonName, columns);
assert(sum(latColumn)==1, 'Could not locate the latitude column name in the site metadata');
assert(sum(lonColumn)==1, 'Could not locate the longitude column name in the site metadata');

% Get proxy metadata
ID = proxies(:,1);
type = proxies(:,2);
lat = str2double(proxies(:,latColumn));
lon = str2double(proxies(:,lonColumn));
depth = str2double(proxies(:,9));
cleaning = str2double(proxies(:,10));
species = proxies(:,11);
nSite = numel(ID);

% Validate species strings
species = validateSpecies(species);

% Locate the different types of records
uk = type=="uk";
tex = type=="tex";
mg = type=="mg";

% Get the seasonal window for each proxy
months = cell(nSite, 1);
monthNames = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
for s = 1:nSite
    if uk(s)
        months(s) = checkSeasonality(lat(s), lon(s));
    elseif tex(s)
        months(s) = {1:12};
    elseif mg(s)
        [~,~,season] = get_sea(lat(s), lon(s), species(s));
        season = season{1};
        [~, months{s}] = ismember(season, monthNames);
    end
end

% Get omega and pH values for Mg/Ca
omega = NaN(nSite, 1);
pH = NaN(nSite, 1);
[omega(mg), pH(mg)] = omgph(lat(mg), lon(mg), depth(mg));

% Get the ensemble and preallocate metadata.
ens = ensemble(ensembleName);
Ye = NaN(nSite, ens.nMembers);

% Load the monthly TOS and SOS variables. Locate NaN values
tos = ens.useVariables("tos_monthly");
[tos, tosMeta] = tos.load;
tosNAN = isnan(tos);

sos = ens.useVariables("sos_monthly");
[sos, sosMeta] = sos.load;
sosNAN = isnan(sos);

% Create a progress bar. Set it to delete when this function exits
message = sprintf('Estimating %s proxies', label);
h = waitbar(0, message);
deleteBar = onCleanup( @()delete(h) );

% Create a forward model for each proxy site
for s = 1:nSite
    if uk(s)
        model = PSM.bayspline;
    elseif tex(s)
        model = PSM.bayspar(lat(s), lon(s));
    elseif mg(s)
        model = PSM.baymag(age, cleaning(s), species(s), 'omega', omega(s), 'pH', pH(s));
    end    

    % Get seasonal TOS for each site. Also get SOS for Mg/Ca
    coordinates = [lat(s), lon(s)];
    siteTOS = getSiteVariable(tos, tosMeta, tosNAN, coordinates, months{s});
    if mg(s)
        siteSOS = getSiteVariable(sos, sosMeta, sosNAN, coordinates, months{s});
    end

    % Run model using appropriate inputs
    if mg(s)
        X = [siteTOS; siteSOS];
    else
        X = siteTOS;
    end
    Ye(s,:) = model.estimate(X);
    
    % Update progress
    waitbar(s/nSite, h);
end

% Export to NetCDF
[nSite,nMembers] = size(Ye);
nSiteCols = numel(columns);
nMemberCols = 2;

file = strcat(label, "-estimates.nc");
nccreate(file, 'sites_columns', 'Dimensions', {'sites_columns', nSiteCols}, 'Format', 'netcdf4', 'Datatype', 'string');
nccreate(file, 'members_columns', 'Dimensions', {'members_columns',nMemberCols}, 'Datatype', 'string');
nccreate(file, 'sites', 'Dimensions', {'sites',nSite,'sites_columns',nSiteCols}, 'Datatype', 'string');
nccreate(file, 'members', 'Dimensions', {'members',nMembers, 'members_columns',nMemberCols}, 'Datatype', 'string');
nccreate(file, 'Ye', 'Dimensions', {'sites',nSite,'members',nMembers}, 'Datatype', 'double');
nccreate(file, 'ensemble_name', 'datatype', 'string');
nccreate(file, 'time', 'datatype', 'double');
nccreate(file, 'latColumn', 'datatype', 'string');
nccreate(file, 'lonColumn', 'datatype', 'string');

ncwriteatt(file, 'sites_columns', 'Description', 'The type of metadata stored along each column of site');
ncwriteatt(file, 'members_columns', 'Description', 'The type of metadata stored along each column of members');
ncwriteatt(file, 'sites', 'Description', 'The proxy sites (and associated metadata)');
ncwriteatt(file, 'members', 'Description', 'The ensemble members');
ncwriteatt(file, 'Ye', 'Description', 'Proxy Estimates');
ncwriteatt(file, 'ensemble_name', 'Description', 'The name of the ensemble used to generate the estimates');
ncwriteatt(file, 'time', 'Description', 'The time value used to implement the BayMAG seawater correction');
ncwriteatt(file, 'time', 'Units', 'Ma');
ncwriteatt(file, 'latColumn', 'The name of the site metadata column (see site_columns) used as latitude coordinates for the estimates');
ncwrtieatt(file, 'lonColumn', 'The name of the site metadata columns (see site_columns) used as longitude coordinates for the estimates');

ncwrite(file, 'sites_columns', columns');
ncwrite(file, 'members_columns', ["Model","Experiment"]);
ncwrite(file, 'sites', proxies);
ncwrite(file, 'members', tosMeta.members("run"));
ncwrite(file, 'Ye', Ye);
ncwrite(file, 'ensemble_name', string(ensembleName));
ncwrite(file, 'time', age);
ncwrite(file, 'latColumn', string(latName));
ncwrite(file, 'lonColumn', string(lonName));

end

%% Utilities
function[species] = validateSpecies(species)

% Locate species indicator strings
sacculifer = contains(species, "sacculifer");
bulloides = contains(species, "bulloides");
sinistral = contains(species, "sinistral");
none = strcmp(species, "");

% Require a single label for everything
nLabel = sacculifer + bulloides + sinistral + none;
missing = nLabel==0;
multiple = nLabel>1;
if any(missing)
    s = find(missing, 1);
    error('Proxy %.f does not have a valid species string', s);
elseif any(multiple)
    s = find(multiple, 1);
    error('Proxy %.f matches multiple species strings', s);
end

% Replace with valid strings
species(sacculifer) = "sacculifer";
species(bulloides) = "bulloides";
species(sinistral) = "incompta";

end
function[Y] = getSiteVariable(X, Xmeta, Xnan, coordinates, months)

% Preallocate
nMembers = Xmeta.nMembers;
Y = NaN(12, nMembers);

% Get the 12 monthly values for each ensemble member
% (different experiments may use different spatial grids, so need to search
% each ensemble member individually to avoid NaNs)
variable = Xmeta.variables;
for m = 1:nMembers
    rows = Xmeta.closestLatLon(variable, coordinates, 'exclude', Xnan(:,m));
    Y(:,m) = X(rows, m);
end

% Get the seasonal mean
Y = Y(months, :);
Y = mean(Y, 1);

end

%% Utility
function[label] = assertStrScalar(label, inputName)
if (isstring(label)&&isscalar(label)) || (ischar(label)&&isrow(label))
    label = string(label);
else
    error('%s must be a string scalar', inputName);
end
end