function[] = estimateProxies(label, age, ensembleName, latName, lonName)
%% estimateProxies  Estimates proxy records for a particular time slice and ensemble
% ----------
%   estimateProxies(label, age, ensembleName, latName, lonName)
%   Estimates the proxy records for a particular time slice and ensemble.
%   Saves the proxy estimates to a NetCDF file in the current directory.
%   The name of saved file will follow the pattern <label>_estimates.nc
%
%   Proxy estimates are generated by running BaySPLINE (uk_forward.m),
%   BaySPAR (tex_forward.m), and BayMAG (baymag_forward_ln.m) on the UK'37,
%   TEX86, and Mg/Ca proxy records, respectively.
%
%   The inputs to the PSMs are located using the latitude-longitude
%   coordinates, or paleo-coordinates, associated with the time-slice being
%   estimated. Each PSM is passed inputs from a particular seasonal mean. 
%   Seasonal windows for the UK'37 record are calculated using the
%   "checkSeasonality.m" function in BaySPLINE. All TEX86 records use
%   annual mean values. Seasonal windows for Mg/Ca are calculated using the
%   "get_sea.m" function from BayMAG. The Mg/Ca PSMs also use parametrized
%   omega and pH values, which are calculated using the "omgph.m" function
%   from BayMAG.
% ----------
%   Inputs:
%       label (string scalar): A label to use for the estimates. The file
%           name for the NetCDF file will follow the pattern
%           <label>_estimates.nc
%       age (numeric scalar): The time metadata for the time slice in which
%           to estimate proxies. This value is used to implement the BayMAG
%           sea water correction. The time value should be in Ma.
%       ensembleName (string scalar): The label of the ensemble to use to
%           generate the proxy estimates.
%       latName (string scalar): The name of the site metadata to use as
%           latitude (paleo)coordinates. Specifically, this should be the name of
%           one of the site metadata columns from "proxies.nc"
%       lonName (string scalar): The name of the site metadata to use as
%           longitude (paleo)coordinates. Specifically, this should be the name of
%           one of the site metadata columns from "proxies.nc"
%
%   Outputs:
%       Creates a NetCDF file named "<label>_estimates.nc" in the current
%       directory.

% Error check data types of inputs
label = assertStrScalar(label, 'label');
assert(isnumeric(age)&&isscalar(age), 'age must be a numeric scalar');
ensembleName = assertStrScalar(ensembleName, 'ensembleName');
latName = assertStrScalar(latName, 'latName');
lonName = assertStrScalar(lonName, 'lonName');

% Get the PSM, season, and coordinates for each site
[models, coordinates, seasons] = buildPSMs(age, latName, lonName);
nSite = numel(models);

% Get the ensemble
ens = ensemble(ensembleName);

% Preallocate estimates, the seasonal TOS and SOS inputs
Ye = NaN(nSite, ens.nMembers);
tosSeasonal = NaN(nSite, ens.nMembers);
sosSeasonal = NaN(nSite, ens.nMembers);

% Load the monthly TOS and SOS variables. Locate NaN values
tos = ens.useVariables("tos_monthly");
[tos, tosMeta] = tos.load;
tosNAN = isnan(tos);

sos = ens.useVariables("sos_monthly");
[sos, sosMeta] = sos.load;
sosNAN = isnan(sos);

% Create a progress bar. Set it to delete when this function exits
message = sprintf('Estimating %s proxies', label);
h = waitbar(0, message);
deleteBar = onCleanup( @()delete(h) );

% Iterate through sites. Note whether the site is for Mg/Ca
for s = 1:nSite
    mg = isa(models{s}, 'PSM.baymag');

    % Get seasonal TOS for each site. Also get SOS for Mg/Ca
    tosSeasonal(s,:) = getSiteVariable(tos, tosMeta, tosNAN, coordinates(s,:), seasons{s});
    if mg
        sosSeasonal(s,:) = getSiteVariable(sos, sosMeta, sosNAN, coordinates(s,:), seasons{s});
    end

    % Run model using appropriate inputs
    if mg
        X = [tosSeasonal(s,:); sosSeasonal(s,:)];
    else
        X = tosSeasonal(s,:);
    end
    Ye(s,:) = models{s}.estimate(X);
    
    % Update progress
    waitbar(s/nSite, h);

    % Convert seasons to string
    seasons{s} = join(string(seasons{s}), ',');
end
seasons = string(seasons);

% Load proxy metadata
proxies = gridfile('proxies').metadata;
columns = proxies.attributes.site_metadata_columns;
proxies = proxies.site;

% Export to NetCDF
[nSite,nMembers] = size(Ye);
nSiteCols = numel(columns);
nMemberCols = 2;

file = strcat(label, "_estimates.nc");
nccreate(file, 'sites_columns', 'Dimensions', {'sites_columns', nSiteCols}, 'Format', 'netcdf4', 'Datatype', 'string');
nccreate(file, 'members_columns', 'Dimensions', {'members_columns',nMemberCols}, 'Datatype', 'string');
nccreate(file, 'sites', 'Dimensions', {'sites',nSite,'sites_columns',nSiteCols}, 'Datatype', 'string');
nccreate(file, 'members', 'Dimensions', {'members',nMembers, 'members_columns',nMemberCols}, 'Datatype', 'string');
nccreate(file, 'Ye', 'Dimensions', {'sites',nSite,'members',nMembers}, 'Datatype', 'double');
nccreate(file, 'tos_seasonal', 'Dimensions', {'sites',nSite,'members',nMembers}, 'Datatype', 'double');
nccreate(file, 'sos_seasonal', 'Dimensions', {'sites',nSite,'members',nMembers}, 'Datatype', 'double');
nccreate(file, 'seasons', 'Dimensions', {'sites',nSite}, 'Datatype', 'string');
nccreate(file, 'ensemble_name', 'datatype', 'string');
nccreate(file, 'time', 'datatype', 'double');
nccreate(file, 'latColumn', 'datatype', 'string');
nccreate(file, 'lonColumn', 'datatype', 'string');

ncwriteatt(file, 'sites_columns', 'Description', 'The type of metadata stored along each column of site');
ncwriteatt(file, 'members_columns', 'Description', 'The type of metadata stored along each column of members');
ncwriteatt(file, 'sites', 'Description', 'The proxy sites (and associated metadata)');
ncwriteatt(file, 'members', 'Description', 'The ensemble members');
ncwriteatt(file, 'Ye', 'Description', 'Proxy Estimates');
ncwriteatt(file, 'tos_seasonal', 'Description', 'The seasonal TOS (sea surface temperature) values used to run the PSMs');
ncwriteatt(file, 'tos_seasonal', 'Units', 'Celsius');
ncwriteatt(file, 'sos_seasonal', 'Description', 'The seasonal SOS (sea surface salinity) values used to run the PSMs');
ncwriteatt(file, 'sos_seasonal', 'Units', 'g/kg');
ncwriteatt(file, 'sos_seasonal', 'Units_Equivalent', 'psu');
ncwriteatt(file, 'seasons', 'Description', 'The calendar months used to compute the seasonal values for each site');
ncwriteatt(file, 'ensemble_name', 'Description', 'The name of the ensemble used to generate the estimates');
ncwriteatt(file, 'time', 'Description', 'The time value used to implement the BayMAG seawater correction');
ncwriteatt(file, 'time', 'Units', 'Ma');
ncwriteatt(file, 'latColumn', 'Description', 'The name of the site metadata column (see site_columns) used as latitude coordinates for the estimates');
ncwriteatt(file, 'lonColumn', 'Description', 'The name of the site metadata columns (see site_columns) used as longitude coordinates for the estimates');

ncwrite(file, 'sites_columns', columns');
ncwrite(file, 'members_columns', ["Model","Experiment"]);
ncwrite(file, 'sites', proxies);
ncwrite(file, 'members', tosMeta.members("run"));
ncwrite(file, 'Ye', Ye);
ncwrite(file, 'tos_seasonal', tosSeasonal);
ncwrite(file, 'sos_seasonal', sosSeasonal);
ncwrite(file, 'seasons', seasons);
ncwrite(file, 'ensemble_name', string(ensembleName));
ncwrite(file, 'time', age);
ncwrite(file, 'latColumn', string(latName));
ncwrite(file, 'lonColumn', string(lonName));

end

%% Utilities
function[Y] = getSiteVariable(X, Xmeta, Xnan, coordinates, months)

% Preallocate
nMembers = Xmeta.nMembers;
Y = NaN(12, nMembers);

% Get the 12 monthly values for each ensemble member
% (different experiments may use different spatial grids, so need to search
% each ensemble member individually to avoid NaNs)
variable = Xmeta.variables;
for m = 1:nMembers
    rows = Xmeta.closestLatLon(variable, coordinates, 'exclude', Xnan(:,m));
    Y(:,m) = X(rows, m);
end

% Get the seasonal mean
Y = Y(months, :);
Y = mean(Y, 1);

end

%% Utility
function[label] = assertStrScalar(label, inputName)
if (isstring(label)&&isscalar(label)) || (ischar(label)&&isrow(label))
    label = string(label);
else
    error('%s must be a string scalar', inputName);
end
end