function[] = buildProxyGridfile(folder)
%% buildProxyGridfile  Builds a gridfile for the proxy records
% ----------
%   buildProxyGridfile(folder)
%   Builds a gridfile catalogue named "proxies.grid" for the proxy records. 
%   Includes metadata for the assimilation time slices and for the individual proxy sites. Proxy site
%   metadata includes site ID, proxy type, current/paleo latitudes and
%   longitudes, and (when applicable) depth, cleaning method, and species. 
%   The proxy data source file should be named "proxies.nc" and can be
%   generated by running the "proxyData.organize" method.
% ----------
%   Inputs:
%      folder (string scalar): The name of the folder holding the
%          "proxies.nc" data source file. The folder name should be
%          relative to the current directory
%
%   Outputs:
%      Creates a gridfile named "proxies.nc" in the current directory.

% Error check
if ~((isstring(folder)&&isscalar(folder)) || (ischar(folder)&&isrow(folder)))
    error('folder must be a string scalar');
end
folder = string(folder);
assert(isfolder(folder), 'Could not locate folder: %s', folder);

% Get the proxy NetCDF file and check it exists
% file = fullfile(folder, 'proxies.nc');
% PlioVar option:
file = fullfile(folder, 'proxiesPlioVar.nc');
assert(isfile(file), 'Could not locate "proxies.nc" within the folder');

% Read metadata from file
IDs = ncread(file, 'site');
lats = ncread(file, 'lat');
lons = ncread(file, 'lon');
pLat325 = ncread(file, 'pLat325');
pLon325 = ncread(file, 'pLon325');
pLat475 = ncread(file, 'pLat475');
pLon475 = ncread(file, 'pLon475');
depth = ncread(file, 'depth');
cleaning = ncread(file, 'cleaning');
type = ncread(file, 'type');
species = ncread(file, 'species');

time = ncread(file, 'time');
timeBounds = ncread(file, 'timeBounds');

% Build metadata object
coords = string([lats, lons, pLat325, pLon325, pLat475, pLon475, depth]);
site = [IDs, type, coords, cleaning, species];
site(ismissing(site)) = "";
metadata = gridMetadata('site', site, 'time', time);
metadata = metadata.addAttributes(...
    'site_metadata_columns', ["ID","type","lat","lon","pLat325","pLon325","pLat475","pLon475","depth","cleaning","species"],...
    'timeBounds', timeBounds);

% Create gridfile. Add source file
proxies = gridfile.new('proxiesPlioVar', metadata, 'overwrite');
proxies.add('netcdf', file, 'data', ["site","time"], metadata);

end